CREATE DATABASE EMPRESA;
GO

USE EMPRESA;
GO

CREATE TABLE PESSOA(
 idPessoa SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomePessoa VARCHAR(20) NOT NULL
);
GO

CREATE TABLE TELEFONE(
 idTelefone SMALLINT PRIMARY KEY IDENTITY(1,1),
 idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
 numeroTelefone VARCHAR(15) NOT NULL
);
GO

CREATE TABLE EMAIL(
 idEmail INT PRIMARY KEY IDENTITY(1,1),
 idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
 end_email VARCHAR(256) NOT NULL
);
GO

CREATE TABLE CNH(
 idCNH SMALLINT PRIMARY KEY IDENTITY(1,1),
 idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
 descricao CHAR(11) NOT NULL UNIQUE
);
GO

INSERT PESSOA (nomePessoa)
VALUES ('SAULO'), ('LUCAS')

SELECT * FROM PESSOA


INSERT TELEFONE (idPessoa, numeroTelefone)
VALUES (1,'999999999'),(2, '888888888')

SELECT * FROM TELEFONE

INSERT EMAIL(idPessoa,end_email)
VALUES (1,'s.saulo@email.com'),(2, 'l.aragao@email.com')

SELECT * FROM EMAIL

INSERT CNH(idPessoa,descricao)
VALUES (1,'12432'),(2, '15213')

SELECT * FROM CNH

