CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE EMPRESA(
 idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomeEmpresa VARCHAR(30) NOT NULL
);
GO

CREATE TABLE MARCA(
 idMarca SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomeMarca VARCHAR(20) NOT NULL
);
GO

CREATE TABLE MODELO(
 idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
 idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
 nomeModelo VARCHAR(25) NOT NULL
);
GO


CREATE TABLE VEICULO(
 idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
 idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
 idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
 placa VARCHAR(10) NOT NULL
);
GO

CREATE TABLE CLIENTE(
 idCLiente SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomeCliente VARCHAR(25) NOT NULL,
 cpfCliente VARCHAR(13) NOT NULL
);
GO

CREATE TABLE ALUGUEL(
 idAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
 idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
 idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente)
);
GO

INSERT INTO EMPRESA (nomeEmpresa)
VALUES ('Localiza'), ('Unidas')

SELECT * FROM EMPRESA

INSERT INTO MARCA (nomeMarca)
VALUES ('FORD'),('HYUNDAI')


SELECT * FROM MARCA

INSERT INTO MODELO (idMarca, nomeModelo)
VALUES (1, 'Ford Mustang'), (1, 'Ford KA'), (2,'HB20'), (2,'Sonata')

SELECT *FROM MODELO

INSERT INTO VEICULO (idModelo, idEmpresa, placa)
VALUES (1, 1, '137289'), (4, 2,'774455')

SELECT *FROM VEICULO

INSERT INTO CLIENTE (nomeCliente, cpfCliente)
VALUES ('Nayara','6543489910'),('Saulo','48239089')

SELECT *FROM CLIENTE

INSERT INTO ALUGUEL (idVeiculo, idCliente)
VALUES (1, 1),(2,2)

SELECT *FROM ALUGUEL

SELECT ALUGUEL.dataFim, ALUGUEL.dataFim, CLIENTE.nomeCliente, MODELO.nomeModelo FROM ALUGUEL
INNER JOIN CLIENTE
ON ALUGUEL.idCliente = CLIENTE.idCLiente
INNER JOIN VEICULO
ON ALUGUEL.idVeiculo = VEICULO.idVeiculo
INNER JOIN MODELO
ON MODELO.idModelo = VEICULO.idModelo;
GO

SELECT ALUGUEL.dataFim, ALUGUEL.dataFim, CLIENTE.nomeCliente, MODELO.nomeModelo FROM ALUGUEL
INNER JOIN CLIENTE
ON ALUGUEL.idCliente = CLIENTE.idCLiente
INNER JOIN VEICULO
ON ALUGUEL.idVeiculo = VEICULO.idVeiculo
INNER JOIN MODELO
ON MODELO.idModelo = VEICULO.idModelo
WHERE CLIENTE.nomeCliente = 'LUCAS';
GO
