USE PCLINICS;
GO

INSERT INTO CLINICA(nomeClinica)
VALUES ('PLENA'), ('COBASE');
GO

SELECT * FROM CLINICA

INSERT INTO VETERINARIO(idClinica, nomeVet)
VALUES (2, 'LUCAS'), (1, 'SAULO'), (1, 'JOÃO');
GO

SELECT * FROM VETERINARIO


INSERT INTO TIPOPET(nomeTipo)
VALUES ('GATO'), ('CACHORRO'), ('COELHO');
GO

SELECT * FROM TIPOPET

INSERT INTO RACA(idTipo, nomeRaca)
VALUES (1, 'MUCHKIN'), (2, 'RETRIEVER'), (3, 'MINI LOP');
GO

SELECT * FROM RACA


INSERT INTO DONO(nomeDono)
VALUES ('LUCAS'), ('SAULO');
GO

SELECT * FROM DONO

INSERT INTO PET(idRaca, idDono, nomePet)
VALUES (2, 2, 'TOBBY'), (1, 1, 'SUZANE');
GO

SELECT * FROM PET

INSERT INTO ATENDIMENTO(idPet, idVet)
VALUES (2,1), (1,3);
GO

SELECT * FROM ATENDIMENTO

SELECT VETERINARIO.nomeVet, VETERINARIO.crmv, CLINICA.nomeClinica FROM VETERINARIO
INNER JOIN CLINICA
ON VETERINARIO.idClinica = CLINICA.idClinica
WHERE CLINICA.nomeClinica = 'PLENA';
GO

SELECT RACA.nomeRaca FROM RACA
WHERE RACA.nomeRaca LIKE 'S%';
GO

SELECT TIPOPET.nomeTipo FROM TIPOPET
WHERE TIPOPET.nomeTipo LIKE '%O';
GO

SELECT PET.nomePet, DONO.nomeDono FROM PET
INNER JOIN DONO
ON PET.idDono = DONO.idDono;
GO

SELECT VETERINARIO.nomeVet, PET.nomePet, RACA.nomeRaca, TIPOPET.nomeTipo, DONO.nomeDono, CLINICA.nomeClinica FROM ATENDIMENTO
INNER JOIN VETERINARIO
ON ATENDIMENTO.idVet = VETERINARIO.idVet
INNER JOIN PET
ON ATENDIMENTO.idPet = PET.idPet
INNER JOIN RACA
ON PET.idRaca = RACA.idRaca
INNER JOIN TIPOPET
ON RACA.idTipo = TIPOPET.idTipo
INNER JOIN DONO
ON PET.idDono = DONO.idDono
INNER JOIN CLINICA
ON VETERINARIO.idClinica = CLINICA.idClinica;
GO