USE PCLINICS;
GO

INSERT INTO CLINICA(nomeClinica)
VALUES ('PLENA'), ('COBASE');
GO

SELECT * FROM CLINICA

INSERT INTO VETERINARIO(idClinica, nomeVet)
VALUES (2, 'LUCAS'), (1, 'SAULO'), (1, 'JOÃO');
GO

SELECT * FROM VETERINARIO


INSERT INTO TIPOPET(nomeTipo)
VALUES ('GATO'), ('CACHORRO'), ('COELHO');
GO

SELECT * FROM TIPOPET

INSERT INTO RACA(idTipo, nomeRaca)
VALUES (1, 'MUCHKIN'), (2, 'RETRIEVER'), (3, 'MINI LOP');
GO

SELECT * FROM RACA


INSERT INTO DONO(nomeDono)
VALUES ('LUCAS'), ('SAULO');
GO

SELECT * FROM DONO

INSERT INTO PET(idRaca, idDono, nomePet)
VALUES (2, 2, 'TOBBY'), (1, 1, 'SUZANE');
GO

SELECT * FROM PET

INSERT INTO ATENDIMENTO(idPet, idVet)
VALUES (2,1), (1,3);
GO

SELECT * FROM ATENDIMENTO