USE OPTUS;
GO

INSERT INTO ARTISTA(nomeArtista)
VALUES ('SIA'), ('ALT-J');
GO

SELECT * FROM ARTISTA


INSERT INTO ESTILO(nomeEstilo)
VALUES ('POP'), ('INDIE'), ('ROCK');
GO

SELECT * FROM ESTILO

INSERT INTO ALBUM(idArtista, idEstilo, nomeAlbum)
VALUES (1, 1, 'ALIVE'), (2, 3, 'BREEZEBLOCKS');
GO

SELECT * FROM ALBUM

INSERT INTO USUARIO(nomeUsuario)
VALUES ('LUCAS'), ('SAULO'), ('ANA');
GO

SELECT * FROM USUARIO

DELETE FROM USUARIO
WHERE idUsuario = 1;
GO